services:
  remote-gemini:
    build: .
    ports:
      - "7681:7681"
    command: gemini --show-memory-usage
    environment:
      TTYD_USER: user
      TTYD_PASS: pass123
    volumes:
      - ~/.gemini:/root/.gemini
